// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package refsdb

import (
	"context"
)

const createRecord = `-- name: CreateRecord :execrows
INSERT INTO refs (name, record) VALUES (?, ?)
ON CONFLICT (name) DO NOTHING
`

type CreateRecordParams struct {
	Name   []byte
	Record []byte
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRecord, arg.Name, arg.Record)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAllRecords = `-- name: DeleteAllRecords :exec
DELETE FROM refs
`

func (q *Queries) DeleteAllRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRecords)
	return err
}

const deleteRecord = `-- name: DeleteRecord :execrows
DELETE FROM refs WHERE name = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, name []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecord, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecordIf = `-- name: DeleteRecordIf :execrows
DELETE FROM refs WHERE name = ?1 AND record = ?2
`

type DeleteRecordIfParams struct {
	Name      []byte
	OldRecord []byte
}

func (q *Queries) DeleteRecordIf(ctx context.Context, arg DeleteRecordIfParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecordIf, arg.Name, arg.OldRecord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecord = `-- name: GetRecord :one
SELECT record FROM refs WHERE name = ?
`

func (q *Queries) GetRecord(ctx context.Context, name []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRecord, name)
	var record []byte
	err := row.Scan(&record)
	return record, err
}

const listRecords = `-- name: ListRecords :many
SELECT name, record FROM refs ORDER BY name
`

func (q *Queries) ListRecords(ctx context.Context) ([]Ref, error) {
	rows, err := q.db.QueryContext(ctx, listRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ref{}
	for rows.Next() {
		var i Ref
		if err := rows.Scan(&i.Name, &i.Record); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRecord = `-- name: PutRecord :exec
INSERT INTO refs (name, record) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET record = excluded.record
`

type PutRecordParams struct {
	Name   []byte
	Record []byte
}

func (q *Queries) PutRecord(ctx context.Context, arg PutRecordParams) error {
	_, err := q.db.ExecContext(ctx, putRecord, arg.Name, arg.Record)
	return err
}

const replaceRecord = `-- name: ReplaceRecord :execrows
UPDATE refs SET record = ?1
WHERE name = ?2 AND record = ?3
`

type ReplaceRecordParams struct {
	Record    []byte
	Name      []byte
	OldRecord []byte
}

func (q *Queries) ReplaceRecord(ctx context.Context, arg ReplaceRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceRecord, arg.Record, arg.Name, arg.OldRecord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
